# This is for the exploratory analysis. It assumes the workspace generated by analysis3.R.

library(caret)
source('interpretationFunctions.R')

#head(build.summary.df(curr.data$testing$target.stars, stack.predictf(curr.data$testing)))

plot.results(curr.data$testing$target.stars, stack.predictf(curr.data$testing), 
			 col="yellow")#, save.as.png="images/results.png")
			 
#sum.data <- build.summary.df(curr.data$testing$target.stars, stack.predictf(curr.data$testing))
