# This is for the exploratory analysis. It assumes the workspace generated by analysis3.R.
source('exploratoryFunctions.R')



dstmp <- read.csv('review_data_15k.csv')
dstmp <- read.csv('review_data_100k.csv')
#build.wordcloud('review_data_15k.csv')
build.wordcloud(dstmp)
#stars.compare.wordplot(dstmp)
stars.compare.wordplot(dstmp, layout=c(1,3), max.percentile=0.98)
stars.compare.wordplot(dstmp, use.stars=c(1, 5), layout=c(1, 2), max.percentile=0.85, save.as.png="images/stars-1-5.png")
stars.compare.wordplot(dstmp, use.stars=1, layout=c(1, 1), max.percentile=0.85, save.as.png="images/stars-1.png")
stars.compare.wordplot(dstmp, use.stars=5, layout=c(1, 1), max.percentile=0.85, save.as.png="images/stars-5.png")
